---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-audit-action
name: 'ðŸ Python Dependency Audit'
description: 'Check Python dependencies for known security vulnerabilities'

inputs:
  # Mandatory
  python_version:
    description: 'Python version used to perform audit'
    required: true
  # Optional
  artefact_name:
    # Useful when building for multiple platforms/architectures
    # Can be used to avoid downloading artefacts with conflicting names
    description: 'Artefact name to download (defaults to project name)'
    required: false
    # type: string
  permit_fail:
    description: 'Continue/pass even when the audit fails'
    required: false
    # type: boolean
    default: 'false'
  artefact_path:
    description: 'Path/location to build artefacts'
    # type: string
    required: false
    default: 'dist'
  summary:
    description: 'Whether to generate summary output'
    # type: boolean
    required: false
    default: 'true'
  path_prefix:
    description: 'Directory location containing project code'
    # type: string
    required: false
    default: ''
  ignore_vulns:
    description: 'Vulnerability IDs to ignore (whitespace separated)'
    # type: string
    required: false
    default: 'GHSA-4xh5-x5gv-qwph'

runs:
  using: 'composite'
  steps:
    - name: 'Extract Python project naming/metadata'
      id: naming
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-project-name-action@a8287d8627a34a40aacc33f73348dfb0b47b6cea # v0.1.5
      with:
        path_prefix: "${{ inputs.path_prefix }}"

    - name: 'â¬‡ Download build artefacts'
      # yamllint disable-line rule:line-length
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        # yamllint disable-line rule:line-length
        name: "${{ inputs.artefact_name || env.python_project_name }}"
        path: "${{ inputs.artefact_path }}"

    - name: "Setup Python ${{ inputs.python_version }}"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "${{ inputs.python_version }}"

    - name: 'Cache Python dependencies'
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v4.0.2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
          ~/.cache/pipenv
          .venv
          .tox
        # yamllint disable rule:line-length
        key: >-
          python-${{ runner.os }}-${{ runner.arch }}-${{ inputs.python_version }}-
          ${{ hashFiles('**/requirements*.txt', '**/pyproject.toml', '**/poetry.lock', '**/Pipfile*', '**/setup.py', '**/setup.cfg') }}
        restore-keys: |
          python-${{ runner.os }}-${{ runner.arch }}-${{ inputs.python_version }}-
          python-${{ runner.os }}-${{ runner.arch }}-
        # yamllint enable rule:line-length

    - name: 'Install build products/dependencies'
      shell: bash
      run: |
        # Install build products/dependencies
        path_prefix="${{ inputs.path_prefix }}"
        echo 'Upgrading: pip, setuptools'
        python -m pip install --disable-pip-version-check \
          -q --upgrade pip setuptools
        echo 'Installing built package(s) and dependencies'
        for wheel in ${{ inputs.artefact_path }}/*.whl; do
                pip install -q "$wheel"
        done
        # Check for requirements.txt in path_prefix if provided
        req_file="${path_prefix:+$path_prefix/}requirements.txt"
        if [ -f "$req_file" ]; then
          echo "Installing dependencies from: $req_file"
          pip install -q -r "$req_file"
        fi

    - name: 'Auditing with: pypa/gh-action-pip-audit'
      if: ${{ inputs.permit_fail == 'false' }}
      # yamllint disable-line rule:line-length
      uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
      with:
        inputs: "${{ inputs.path_prefix }}"
        summary: "${{ inputs.summary }}"
        ignore-vulns: "${{ inputs.ignore_vulns }}"

    - name: 'Auditing with: pypa/gh-action-pip-audit'
      if: ${{ inputs.permit_fail == 'true' }}
      continue-on-error: true
      # yamllint disable-line rule:line-length
      uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
      with:
        inputs: "${{ inputs.path_prefix }}"
        summary: "${{ inputs.summary }}"
        ignore-vulns: "${{ inputs.ignore_vulns }}"
